// SPDX-License-Identifier: MIT
/*
 * Copyright © 2026 Charles Henderson
 * All rights reserved.
 */
pragma solidity ^0.8.20;

contract AISovereignVault {
    address public immutable aiAgentSigner;
    mapping(bytes32 => bool) public executedPayloads;

    event AIExecutionSuccess(bytes32 indexed payloadHash, string decisionReason);

    constructor(address _aiAgentSigner) {
        require(_aiAgentSigner != address(0), "Invalid agent address");
        aiAgentSigner = _aiAgentSigner;
    }

    /// @notice Executes an action approved by the off-chain AI Agent
    /// @param target The destination address for the transaction
    /// @param value The amount of native asset to transfer
    /// @param data The calldata to execute on the target
    /// @param decisionReason The text string explaining the AI's logical analysis
    /// @param signature The ECDSA signature generated by the AI Agent
    function executeAIAction(
        address target,
        uint256 value,
        bytes calldata data,
        string calldata decisionReason,
        bytes calldata signature
    ) external payable {
        // Construct the payload hash matching the off-chain data
        bytes32 payloadHash = keccak256(abi.encodePacked(target, value, data, decisionReason));
        bytes32 ethSignedMessageHash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", payloadHash));

        require(!executedPayloads[payloadHash], "Action already executed");
        require(recoverSigner(ethSignedMessageHash, signature) == aiAgentSigner, "Unauthorized AI Signature");

        executedPayloads[payloadHash] = true;

        // Execute the approved action
        (bool success, ) = target.call{value: value}(data);
        require(success, "Underlying transaction execution failed");

        emit AIExecutionSuccess(payloadHash, decisionReason);
    }

    function recoverSigner(bytes32 _ethSignedMessageHash, bytes memory _signature) internal pure returns (address) {
        require(_signature.length == 65, "Invalid signature length");
        bytes32 r;
        bytes32 s;
        uint8 v;

        assembly {
            r := mload(add(_signature, 32))
            s := mload(add(_signature, 64))
            v := byte(0, mload(add(_signature, 96)))
        }

        return ecrecover(_ethSignedMessageHash, v, r, s);
    }

    receive() external payable {}
}
