name: Nexus Cloud Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Configure CMake
      # Added -Wno-dev and -DCMAKE_POLICY_DEFAULT_CMP0167=OLD to bypass the Boost error
      run: cmake -B build -DBUILD_TESTS=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_POLICY_DEFAULT_CMP0167=OLD

    - name: Compile Core
      run: cmake --build build -j4
