name: Nexus Cloud Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false

    - name: Install Dependencies
      run: |
        sudo apt-get update
        # Added protobuf-compiler and libprotobuf-dev to system deps
        sudo apt-get install -y clang libboost-all-dev libgtest-dev protobuf-compiler libprotobuf-dev
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Configure CMake
      run: >
        cmake -B build 
        -DBUILD_TESTS=OFF 
        -DCMAKE_C_COMPILER=clang 
        -DCMAKE_CXX_COMPILER=clang++ 
        -DCMAKE_POLICY_DEFAULT_CMP0167=OLD 
        -DProtobuf_USE_STATIC_LIBS=OFF
        -Dgtest_DIR=/usr/src/gtest

    - name: Compile Core
      run: cmake --build build -j4
